services:
  homepage-lite:
    image: ghcr.io/jkerdreux-imt/homepage-lite:latest
    # image: homepage-lite:latest
    ports:
      - "8888:8888"
    volumes:
      - ./:/app/config/
    restart: unless-stopped
